
# HTTP Server
server:
  port: 12342  # HTTP (Tomcat) port


spring:
  application:
    name: ts-loginregister-service

  zipkin:
    baseUrl: http://zipkin:9411/
  sleuth:
    sampler:
      percentage: 1.0